### ISSUE TITLE
How can i update server code without restart server

### ISSUE THREAD

**Issue by trananhmanh89** [szymmis/vite-express#1]
Hi,
Thanks for your work. 
I have a question. 
How can i update server code without restart node server?

**Comment by szymmis** [comment]
Hi @trananhmanh89 :wave: 
If you'd like to not have to manually restart node server every time you change code, you can use [nodemon](https://www.npmjs.com/package/nodemon) package, so that every time you make a code change, it will automatically restart your server. If what you want is to have some kind of hot replacement of server-side code without restarting the node process then unfortunately I won't be able to help you.

**Comment by angelhdzmultimedia** [comment]
> Hi @trananhmanh89 👋 If you'd like to not have to manually restart node server every time, you can use [nodemon](https://www.npmjs.com/package/nodemon) package, so that every time you make a code change, it will automatically restart your server. If what you want is to have some kind of hot replacement of server-side code without restarting the node process then unfortunately I won't be able to help you.

I tried with `node --watch` and it creates an infinite loop. 
I'm pretty sure this is because when the frontend code is run, some file gets modified or created, and  causes the server code to restart.

**Comment by crutch12** [comment]
@angelhdzmultimedia I found - it every time generates `vite.config.ts.timestamp-1721912890454-4d4be18b59d59.mjs` file in root folder

So you should ignore it:
```sh
# tsx watch example
tsx watch --ignore "vite.config.*" server/index.js
```
