### ISSUE TITLE
404 after deploying to amplify

### ISSUE THREAD

**Issue by laclance** [szymmis/vite-express#120]
Works fine locally but api calls give a 404 when deployed to aws amplify, maybe amplify requires some additional config?

**Comment by laclance** [comment]
Made a minimal example https://github.com/laclance/vite-express

**Comment by laclance** [comment]
Same is happening when deploying statically to s3.

**Comment by laclance** [comment]
I have tried adding `ViteExpress.config({ mode: 'production' });`

**Comment by szymmis** [comment]
Hi @laclance, sorry for late response. I'm afraid that it isn't possible to use Amplify nor S3 to host express server because the node instance needs to be running and handling requests. 
I don't have much knowledge about AWS in general, does typical express server works with Amplify? If it does then it's definitely worth investigating why `vite-express` doesn't work with Amplify.

You could use something that let's you run a server instance like EC2, that's for sure or use something other than from the AWS suite like [Render](https://render.com/) which have free tier.

I would like to know if you want to use `vite-express` in an existing app that you host on Amplify or are you deploying it for the first time, so I can better understand your use case and figure out if I can help you with that.

**Comment by laclance** [comment]
Thank you that's what I figured, it is an existing app but still in alpha, switched to use render for now.

**Comment by laclance** [comment]
Yes

**Comment by szymmis** [comment]
Great to hear that, I will proceed and close this issue. If you have any questions feel free to ask!
