### ISSUE TITLE
Conflict with express

### ISSUE THREAD

**Issue by Joanzo** [szymmis/vite-express#21]
Hello, this is a really awesome plugin. 
When i try to set router for homepage example:

` app.get("/", (_, res) => {
     res.render(page, data);
  });`

It's intermittently showing page from express server
sometime show page from Vite from root index.html

do you know the cause? cheers..

**Comment by anselal** [comment]
@szymmis 
Sorry for hopping, I think I am experiencing the same "issue".
In my setup express is running on port 3001 and reactjs is running on port 5174.
But I can also access the user interface from port 3001 which normally shouldn't happen.

**Comment by szymmis** [comment]
No need to be sorry about giving input @anselal. I see that there is some misconception about how vite-express package is working. What you described is how it should work. What you use vite-express for is to join vite with your backend to ease fullstack app development. The same content that is server Vite dev served is served by your Express server when you access all the get paths that you dont handle yourself. To sum up you shouldn't access frontend content through localhost:5173, you should only use localhost:3001 or whatever port you choosed for your backend. That way you can easily fetch your backend from the client just by doing fetch("/path") instead of fetch("http://localhost:3001") and handle all the CORS stuff etc by yourself. If you want to separately launch vite dev server and Express i guess you dont need that package that much.

I hope I made that clear. If you have any more questions feel free to ask, but I'll close this issue for now.
