### ISSUE TITLE
how to connect from other devices?

### ISSUE THREAD

**Issue by Richard-So** [szymmis/vite-express#23]
Hi, previously I was able to connect to x.x.x.x:5173 (where x.x.x.x is the IP address) from my iPad or from iPhone using script in package.json as shown below.
"dev": "vite --host"

I was trying to see if I can use this feature using Vite-express but failed to do so. Any idea?

**Comment by Richard-So** [comment]
solved it!

edited vite.config.ts file and edited the defineConfig to have server with my IP address in it.
export default defineConfig({
  plugins: [react()],
  server: {
    host: '192.168.1.68',
  },
})

I wonder if this would be the right approach..?

**Comment by Richard-So** [comment]
solved it!

edited vite.config.ts file and edited the defineConfig to have server with my IP address in it.
export default defineConfig({
plugins: [react()],
server: {
host: 'x.x.x.x',
},
})

I wonder if this would be the right approach..?

**Comment by szymmis** [comment]
Hi @Richard-So, right now there isnt a way to make vite-express print local area network host as with --host flag on Vite, but you could run vite with that flag just to see your computer IP address and then run your vite-express app and just connect to that ip from your phone but of course you would need to use the correct port, so something like 192.168.55.107:3000 and you should be good for now.

I definitely need to think of a way to make this show host available in vite-express.

Thanks a lot for your input!

**Comment by szymmis** [comment]
After consideration, this feature is not possible with the current configuration of vite-express because it is possible to run your server listening process without vite-express `listen` method, but instead use `bind` method to set up evetything. What it means is that vite-express doesn't know what port or host are you listening on, So you cannot show such info as vite with `--host` does.

What is the most imortant here is that you can get your local IP address using whatever method there is (e.g. running Vite with the `--host`, or using `ipconfig` on Windows, etc.), and them use this address with the correct port number to connect to your vite-express instance.

The problem here is that I want vite-express to be as light and thin as it can be so that you can easily integrate it with most of the existing Express apps, and that means there isn't always enough infotmation to do such things as described in this issue.

As always, if you have any questions, feel free to continue to comment on this issue.

Thanks again for highlighting this issue!
