### ISSUE TITLE
PageNotFound

### ISSUE THREAD

**Issue by glenndimaano** [szymmis/vite-express#25]
how to re-render client on app.get("/") root route?

import express from "express";
import ViteExpress from "vite-express";

app.get("/hello", (req, res) => {
  res.send("Hello Vite + React!");
});

app.use((req, res, next) { 
const error = new Error(`Page not found - ${req.originalUrl}`)
    res.status(404)
    next(error)
})

app.use((err, req, res, next) { 
const statusCode = res.statusCode === 200 ? 500 : res.statusCode;
    res.status(statusCode)
    res.json({
        message: err.message,
        stack: err.stack
    }))

ViteExpress.listen(app, 3000, () =>
  console.log("Server is listening on port 3000...")
);

`running : npm run dev`

<p>{"message":"Page not found - /","stack":"Error: Page not found - /\n </p>

**Comment by szymmis** [comment]
Hi @glenndimaano, sorry for such a late response. From what I see in code the problem with rendering client files is that you have such middlewares set up that completely block almost all traffic.

```
app.use((req, res, next) => {
  const error = new Error(Page not found - ${req.originalUrl})
  res.status(404)
  next(error)
})
```
This middelware is run on every request, on every request method (GET, POST, etc) and automatically sets the error and code. That's why you get 
```
{"message":"Page not found - /","stack":"Error: Page not found - /\n
```
As a response when you try to request `/` path.

Also this part is confusing
```
app.use((err, req, res, next) => {
  const statusCode = res.statusCode === 200 ? 500 : res.statusCode;
  res.status(statusCode)
  res.json({
    message: err.message,
    stack: err.stack
  })
})
```
If the response statusCode is equal to 200 you shouldn't set it as a 500 which means internal server error, so I guess the code that you posted is incorrect.

If you'd like to send 404 to browser when page is not found you'd need to define some kind of array of allowed paths and then have a middleware that runs on GET requests and filters out those that do not fit into this array of allowed paths. The problem with that is currently you'd have to manually allow also static files.
Maybe it is something that I should add into the library itself, an option to specify which frontend paths are allowed.
If it still relevant let me know if I you are interested, and If you need more help. Thanks a lot for raising and issue!

**Comment by glenndimaano** [comment]
Now I get it, Thanks.
