### ISSUE TITLE
What is the porpuse of the 5173 server?

### ISSUE THREAD

**Issue by aldomeza-dev** [szymmis/vite-express#28]
I'm developing a vite-express-react app and I came across this library, and i saw that it made the connection between vite and express (which is amazing thank you for your work 🙌🏻), but I can't figure out why is there a second service running in `http://localhost:5173`, I a simple express api that returns some text, and a react component to fetch it, in port 3000 it all looks good and well but in http://localhost:5173 I get this:

**Port 5173:**
![image](https://user-images.githubusercontent.com/87845126/227663948-2745c29d-6ab5-4249-b556-b2337932fcaa.png)

**Port 3000:**
![image](https://user-images.githubusercontent.com/87845126/227664016-a7d4ae7b-3d99-4ead-b5c0-81a5dbd7d80c.png)

**Express Code:**
```javascript
const express = require("express");
const ViteExpress = require("vite-express");

const app = express();

app.get("/hello", (req, res) => {
  res.send("Hello Vite + React!");
});


ViteExpress.listen(app, 3000, () =>
  console.log("Server is listening on port 3000...")
);
``` 

**React component:** 
```javascript
import React, { useState, useEffect } from 'react'

function HelloApi() {
  const [helloMsg, setHelloMsg] = useState('')

  useEffect(() => {
    fetch('/hello')
      .then((response) => response.text())
      .then((data) => setHelloMsg(data))
      .catch((error) => console.error(error))
  }, [])

  return (
    <div>
      <h1>{helloMsg}</h1>
    </div>
  )
}

export default HelloApi

``` 

If you could point me to the right direction and explain the other service use I would be forever thankful 🙏🏻

**Comment by szymmis** [comment]
Hi @aldomeza-dev, first of all thanks a lot for providing all of this info, screens and code. It is a lot easier that way to examine the problem. 

When it comes to your question: As you said vite-express makes a connection between your express server and your Vite server. But to have a connection you still need things to have connected. That's why Vite Dev Server still needs to be run in the background when you run your express app, so that they can communicate and your express app can take static files such as .html, .js, images etc from Vite. And as I said Vite server is running in the background so you absolutely don't need to worry about it, and absolutely don't need to open it in the browser. I'm logging info about Vite listening on concrete port because I wanted to make it clear that there is something running in the background that is taking up the port. If I didn't say that, I guess there would be a lot of confusion when you'd try to run something different on that port and saw that it is blocked.

If this explanation isn't enough please let me know. Perhaps I should modify README a little to make it more clear why is there Vite server running in the background and that you shouldn't access your app through it. You should, as you said, open the app at your express server address:port.

As I said before, if you'd have any more questions, feel free to ask and I'd be happy to help. Thanks again for raising an issue, and for preparing every info without any request from my side, great job!

**Comment by aldomeza-dev** [comment]
**Thank you so much** for the explanation and for taking the time to explain it, I guess now that you've explain it it's quite obvious😅, I just have two more questions if that's okay.

_First question:_
Can I use React Router to handle routes? I was planning on using `React Router` since my app will not need SEO, and my main concerns are performance and UX/UI.

_Second question:_
Once I use `vite build` and have the static files, how should I go about running the back-end? I will be using `pm2` to serve the static files but for the express back-end, how should I run it?

For the README modification, you could add a comment in the "🤔 How does it work?" along the lines of...

>**Note 📣:**
To connect the services of Vite and Express, both must be running. To properly see and interact with your app, only access it through your designated Express port (3000 by default). The console log Vite Dev Server is for you to know witch port Vite is using.

Once again, thanks for your time and patience, as an inexperienced programmer I thank you.

**Comment by szymmis** [comment]
No problem with the questions, as long as you have more questions don't be hesitant to ask them!

Answering your questions:
> First question:
Can I use React Router to handle routes? I was planning on using React Router since my app will not need SEO, and my main concerns are performance and UX/UI.

Absolutely! I've developed `vite-express` with using React Router to make these SPA apps in mind. That's why all GET traffic that is not handled explicitly by your express app, is used to serve HTML from Vite Dev Server when in development mode and as static files in production mode, so it should work out of the box. 
You can test it by accessing your server on any path like http://localhost:3000/my/page/whatever and it should serve you the same content that you'll get on http://localhost:3000.

>Second question:
Once I use vite build and have the static files, how should I go about running the back-end? I will be using pm2 to serve the static files but for the express back-end, how should I run it?

To make your server serve static files you need to make sure to run it in `production` mode. You can achieve this by setting `NODE_ENV=production` env variable somehow or use [ViteExpress.config({ mode: "production" });](https://github.com/szymmis/vite-express#configoptions--void). I recommend the former option, that's how it is done in apps scaffolded with [`🏗️ create-vite-express`](https://www.npmjs.com/package/create-vite-express). There is a `start` position in package.json scripts thats runs this command `"start": "NODE_ENV=production ts-node src/server/main.ts"`. Of course you don't need to use ts-node, you can run your server script whatever you want, just wanted to show you how can you run it with the env variable. The way you setup the env variable doesn't matter, it just needs to be set to `production` when you want your server to run in that mode if you choose this option. The reason why I recommend this way is because it doesn't require code modifications specific to production environment. [This article](https://www.twilio.com/blog/working-with-environment-variables-in-node-js-html) might be an interesting read.

I see also that you mention using `pm2`. You just need to run your server and the files will be served automatically, you don't need any separate process for that. I've been using pm2 for some time so I'd definitely recommend it!

If anything isn't clear, just ask and I'll gladly answer.

Also, thanks a lot for your README note recommendation, I love it! I'll just need to fit it into the current description.

**Comment by aldomeza-dev** [comment]
Thank your for the quick respond, and once again, thank you so much, you're a life saver!

**Comment by szymmis** [comment]
Okay, so if you don't have any more questions let me close the issue. Feel free to ask any more questions here or open next issues in the future.
