### ISSUE TITLE
Does is matter which port you use for development?

### ISSUE THREAD

**Issue by ian-hw** [szymmis/vite-express#30]
Does it matter which port you use for development? I'm seeing that two servers are running when I followed the README instructions - one on port 5173 and one on 3000. Is there a way to only run one of these servers?

**Comment by szymmis** [comment]
Hi @ian-hw! It doesn't matter what ports you are running those two but both servers need to be running. One of them is the one you are interested in, it is your express server that you develop, the other one is Vite Dev Server that is used to serve your front-end files in development, so it needs to be running in the background for you to be able to harness its power like HMR and Hot Reload. What is important is that you can completely ignore the Vite server because you won't be interacting with it in any way manually, it is only used by `vite-express` to connect your frontend app with your backend.

**Comment by ian-hw** [comment]
So to clarify, as long as the Vite Dev Server is running in the background, HMR and Hot Reloading will be available on both ports?

**Comment by szymmis** [comment]
Yes, technicaly. They both need to be running, otherwise there is no reason in using `vite-express`. If you run your Express server in production mode there wont be this second server at all.

Long story short: this library was created to automate the process of running your server and vite separately, so that you only need to run your Express app script and it just works.
