### ISSUE TITLE
the application use 2 ports: 5173 and 3000

### ISSUE THREAD

**Issue by stevez** [szymmis/vite-express#33]
When I use 'npm create vite-express' to create a vite-express project, I found the 2 ports are both working: 5173, and 3000
12:18:04 PM [vite-express] Vite is listening http://localhost:5173
12:18:04 PM [vite-express] Running in development mode
Server is listening on port 3000...

both ports are working, can we disable the port 5173?

**Comment by szymmis** [comment]
Hi @stevez, this kind of confusion already happened a few times. You cannot disable a service running on the 5173 port because it is a port that Vite Dev Server is running on and it is necessary to serve all the "front-end" files during development. I guess I should maybe hide the message about Vite listening on port XXXX to avoid the confusion.

**Comment by stevez** [comment]
The thing is not only about the message, the problem is the front end both works on port 3000 and 5176. Even if you hide the message, port 5176 still works. Right now I am trying to migrate my current application to Vite: the app has both front end and bff backend, front end is react, backend is express, both share the same port 3000. I wonder if I use your plugin, will it work for my case?

**Comment by szymmis** [comment]
Yes, they "share" the same port in the sense that you can access your front-end by requesting directly your server port. Everything is working as it should, that way you can only worry about running your express app, and you can access whole your application under the same port, that way we achieve fully full-stack application. As I said, Vite needs to listen on some port in the background, I've just decided to use the same default as Vite is using. You shouldn't access your frontend throught the port that Vite is listening on, that's why I'm thinking about hiding this message to avoid confusion.

In summary, there are not two apps (your react frontend and backend express server) that are running on the same port, they are the same app. It's just that using vite-express you can use your express server to serve the front-end application and your backend routes together without all the hustle of manually running the frontend and server separately. Vite Dev Server is needed in the background to use the power of hot reload, hot module replacement etc.

If right now you have a Vite react app that you are running manually, and a express server that you are running manually too, the way you should use vite-express is you follow the README instruction and start your express app with the `ViteExpress.listen` or use `ViteExpres.bind` and still use your standard `app.listen` and forget about running Vite manully at all. From now on, you should only run your express app, and it should take care of spinning up all the necessary services (Vite) in the background.

**Comment by stevez** [comment]
Thanks for your reply. 
Now I run into another issue, I just noticed the sever.js in your sample code is using commonJS, while our code base use webpack, and both server code and client code use es6 format (import). So I wonder can I use your plugin in the es6 module or we have to convert to commonjs format in order to use the plugin? Or what is your suggestion for us to use es6 module in the server code?

**Comment by stevez** [comment]
Thanks for your reply. 
Now I run into another issue, I just noticed the sever.js in your sample code is using commonJS, while our code base use webpack, and both server code and client code use es6 format (import). So I wonder can I use your plugin in the es6 module or we have to convert to commonjs format in order to use the plugin? Or what is your suggestion for us to use es6 module in the server code?

**Comment by stevez** [comment]
Thanks for your reply. 
Now I run into another issue, I just noticed the sever.js in your sample code is using commonJS, while our code base use webpack, and both server code and client code use es6 format (import). So I wonder can I use your plugin in the es6 module or we have to convert to commonJS  format in order to use the plugin? Or what is your suggestion for us to use es6 module in the server code?

**Comment by stevez** [comment]
Thanks for your reply. 
Now I run into another issue, I just noticed the sever code in your sample code is using commonJS, while in our code base  both server code and client code use es6 format (import). So I wonder can I use your plugin in the es6 module or we have to convert to commonJS  format in order to use the plugin? Or what is your suggestion for us to use es6 module in the server code?

**Comment by szymmis** [comment]
As far as I know and tested it, vite-express should work out of the box both as a commonjs and esmodules module, so there shouldn't be any problems with your current setup. If you'll stumble upon any problems please let me know so I'll be able to help you!

**Comment by aposhtol** [comment]
Yeah, you should hide the message about running on port 5173 since you can't access backend routes from that port but only the ones on port defined in `ViteExpress.listen`

**Comment by szymmis** [comment]
Hi @aposhtol, I've changed it in v0.5.3 so it should be resolved. If there is anything I can help with, feel free to ask or share any insights. I'll close this issue as it shoild be done.
