### ISSUE TITLE
Element-ui On-demand Import ??

### ISSUE THREAD

**Issue by iibrat** [szymmis/vite-express#36]
https://element-plus.org/en-US/guide/quickstart.html#on-demand-import

npm install -D unplugin-vue-components unplugin-auto-import

mponent: EnglishHead
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <App>
warn2 @ runtime-core.esm-bundle

---------------------------------------------------------------------------------------------------
auto-imports.d.ts

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {

}
---------------------------------------------------------------------------------------------------
components.d.ts 

// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    EnglishEditor: typeof import('./src/client/components/EnglishEditor.vue')['default']
    EnglishFoot: typeof import('./src/client/components/EnglishFoot.vue')['default']
    EnglishHead: typeof import('./src/client/components/EnglishHead.vue')['default']
    EnglishList: typeof import('./src/client/components/EnglishList.vue')['default']
    HelloWorld: typeof import('./src/client/components/HelloWorld.vue')['default']
  }
}

-----------------------------------------------------------------------------------------------------------------

**Comment by szymmis** [comment]
Hi @iibrat, could you describe a little bit more what's the issue about? Like do you have a specific problem or a question that you want to ask? If you could provide more info that would be helpful!

**Comment by iibrat** [comment]
抱歉，是我自己的问题。我正在学习编程，你的项目让我在创建项目时方便了很多。如果你愿意，我想知道怎么把这个项目部署到Linux服务器的Docker上。
Sorry, it's my own problem. I am currently learning programming and your project has been very helpful in creating projects. If you are willing, I would like to know how to deploy this project on a Docker container on a Linux server. Thinks!!

**Comment by szymmis** [comment]
Do you have a Dockerfile defining a Node image with all the source code copied? I don't know if you need help only with deploying a container on a server or creating it also? You can deploy your container in two ways:
1. Build an image and push it to [Docker registry](https://docs.docker.com/registry/), then on your server just start an instance of that image. This approach is recommended.
2. You can also push your source code on the server and then build an image.
3. I believe that you can also build an image locally to a file and then somehow transfer that file to your server, maybe by SSH or something but I haven't done it, so I'm not sure about that approach.

I'd say that the first approach is the best, it is also the easiest one. 
- First of all you need to [create a Docker](https://hub.docker.com/signup) account 
- build your image by running this command inside directory with your Dockerfile
`docker build -t your_docker_username/your_image_name .` 
_example: `docker build -t szymmis/my_image .`_
- push this image to the Docker registry
`docker push your_docker_username/your_image_name`
_example: `docker push szymmis/my_image`_
- On your server run the container using your image:
`docker run -p 3000:3000 your_docker_username/your_image_name`

If you are on linux/macos and you get `docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock` try to run the commands with sudo.

If that's an answer that you were looking for, that's great! But otherwise you may need to find an answer in more Docker specific places/tutorials/etc. You can just search the internet for tutorials how to set up and deploy Docker express server because it doesn't differ when you use `vite-express`, it will still be the same.

**Comment by szymmis** [comment]
Will close the issue as it is not directly related to the package itself, but if you have any more questions feel free to just continue the thread.

Thanks a lot @iibrat!
