### ISSUE TITLE
Vite opens port 5173 and not 3000, and no access to vite env from server.js

### ISSUE THREAD

**Issue by cgalpin** [szymmis/vite-express#37]
I am converting an app from CRA to Vite and found this looking for a solution to a custom proxy like I used to have using setupProxy.js to serve some apis, and I *think* this is the right solution for this, but let me know if I am wrong please :)

I believe I have this working with some basic testing, but I have two problems right now, and I hope they have easy fixes.

In my vite.config.ts I configured it to open the browser using

```
server: {
  port: 3000,
  open: true
},
```

But when I run my vite-express powered server with  `node server.js` the browser window opens on `http://localhost:5173` and not `http://localhost:3000`. Is there some way to get it to open port 3000? If not, we will just have to set open to false and I can put a message on the console to open `http://localhost:3000`, but it is a nice feature.

The other problem is I can't figure out how to access the same environment variables available in the app that I have defined in `.env.local` (like use import.meta.VITE_PORT or process.env.VITE_PORT if i define VITE_PORT=3000 in `.env.local` ) in the server.js itself since I need it there too.  They work fine in the app with or without vite-express. Any suggestions?

tia,
charles

**Comment by szymmis** [comment]
Hi @cgalpin. Thanks for opening the issue as I'm glad to help you, and sorry for the late response.

Answering your questions:
- When you set port inside `vite.config.js` you are telling Vite Dev Server to listen on port 3000, but that the port that your express server is listening on. Fact is that this config option doesn't work because it is overwritten inside `vite-express` source code. It is set by default to 5173, and can only be changed using [`ViteExpress.config()`](https://github.com/szymmis/vite-express#configoptions--void) function. That's why it opens on http://localhost:5173, because you told Vite to open the browser when it starts listening, so it does, but the port you specified is not the port that it is listening on, so everything is working as it should, because otherwise you would have a conflict of your express server and vite dev server in the background running on the same port which is not possible. Unfortunately, I'm afraid that you cannot utilize that feature anymore.
- Vite is automatically injecting your .env.local but to use those variables on the backend, in your express app you need to use tools like [dotenv](https://www.npmjs.com/package/dotenv). It is really easy to use and you'll have access to your environment variables on the backend.

If you have any more questions, or something isn't clear, let me know!

**Comment by szymmis** [comment]
As with other issues, I'll close this one because of inactivity, but if you have any questions, feel free to ask!
