### ISSUE TITLE
[question] how to support isomorphic react + express app in vite?

### ISSUE THREAD

**Issue by stevez** [szymmis/vite-express#40]
I am trying to find a solution to migrate from my current project to vite.
The current application is using webpack 4, it has both client and server code: client is using react, server is using express, and since we implement our own way of ssr, and the server code depends on the client code as well. They are all use esm syntax, and transpiled to CommonJS throught webpack/babel. and when the server starts, both client and server share the same port 3000.

My question is how to use your plugin to migrate my app from webpack to vite, is it achievable? Thanks. -- Steve

**Comment by szymmis** [comment]
Hi @stevez, to be honest I don't know if that's possible because this seems quite complicated because you said that you have some custom SSR logic. Maybe you could give a little bit more info about that, but I don't know how to handle server code depending on client code, as `vite-express` was created to handle more classical cases when you have client and server separate and you just want some kind of bridge to make development easier.

**Comment by szymmis** [comment]
As with other issues, I'll close this one because of inactivity, but if you have any questions, feel free to ask!
