### ISSUE TITLE
Hot reloading not working with ngrok reverse proxy

### ISSUE THREAD

**Issue by patryk-smc** [szymmis/vite-express#59]
Hey there,
I use ngrok to serve my app. With plain Vite all, I had to do to make it work was:

```ts
// vite.config.ts
export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
  },
});
```

And then simply run `ngrok http 3000`

However, when using `vite-express`, the page loads but hot reloading does not work. Does anyone have suggestions what goes wrong in this case?

<img width="641" alt="CleanShot 2023-05-25 at 23 29 49@2x" src="https://github.com/szymmis/vite-express/assets/37963339/03e58d4f-9ced-4a7b-a88f-84102b62aef0">

**Comment by szymmis** [comment]
Hi @patryk-smc. I had a moment to check out the problem, and the root cause of it is that when you run plain Vite it takes care of serving http and websockets, but when you run `vite-express` it then uses Vite in middleware mode and there is a problem with websocet ports. In middleware mode Vite assings port 20000 something that is not forwarded by the ngrok proxy. I saw that you created a PR for that, but unfortunately when I've run the tests it fails. I'll try to look if we can use your solution and if not then maybe I'll figure out something else.

**Comment by szymmis** [comment]
Also, I have a strong feeling that this might be something that is solvable by setting HMR port explicitly inside your `vite.config.js` but that's also something that I need to check.

**Comment by patryk-smc** [comment]
@szymmis I was seriously going crazy while messing around with those Vite HMR settings, and by some stroke of luck, passing the server instance ended up being the only solution that worked. Honestly, I have no clue how it actually works. The documentation they provide isn't exactly stellar, so I guess we would have to dig deep into the Vite code to figure it out...

**Comment by szymmis** [comment]
As you said the documentation doesn't contain much information about it. The weird thing is that in some environments your solution is working fine, but when I try to run tests from inside `vite-express` repo it doesn't work. That's definitely something that I need to look into because your solution seems promising from what I've read in the docs.

**Comment by szymmis** [comment]
Sorry to say that, but I won't be able to solve this issue. There is a fundamental problem with how `vite-express` works with `vite` that makes it impossible to fix ngrok problem without massive changes to the code structure. If your solution works then great, but I cannot make it work in my environment that's why I won't bee implementing your fix in #60.

**Comment by kinngh** [comment]
> @szymmis I was seriously going crazy while messing around with those Vite HMR settings, and by some stroke of luck, passing the server instance ended up being the only solution that worked. Honestly, I have no clue how it actually works. The documentation they provide isn't exactly stellar, so I guess we would have to dig deep into the Vite code to figure it out...

Is it possible to get some more details on this? I'm trying the exact same thing on ngrok and having particularly difficult time wrapping my head around this^

**Comment by kinngh** [comment]
> @kinngh What you would like to know?

How to get this working - I'm working on the Shopify app side of things and one of the baseline problems I'm dealing with right now is to run Express' middlewares before a page is served via Vite. It works just fine when using production mode, but in dev mode we need to land on the auth URL. Landing on `/` just won't trigger it^

**Comment by kinngh** [comment]
@patryk-smc makes sense. The PR did fix a bunch of things but also broke more things so I'm not particularly keen on this. I used `patch-package` to persist changes to the package based on your PR but I'm still searching for solutions. For the auth to make sense, here's an overview. When someone lands on `/`, I want to run an Express middleware that checks if the user is authenticated. If they are, proceed to `/` if not, redirect to `/api/auth`.
