### ISSUE TITLE
Loading config using Vite is causing issues

### ISSUE THREAD

**Issue by patryk-smc** [szymmis/vite-express#62]
Loading Vite config in production causes issues in environments that purge dev dependencies. I think it would be better to not load Vite in production at all. See following pattern from vite-plugin-ssr: https://github.com/brillout/vite-plugin-ssr/blob/1a2e701de69314b33d76f5e28963b20c4c92c384/boilerplates/boilerplate-react-ts/server/index.ts#L16-L28

<img width="813" alt="CleanShot 2023-05-31 at 11 49 48@2x" src="https://github.com/szymmis/vite-express/assets/37963339/a498ea96-144a-44dc-b2b9-75d80bcb36e1">

**Comment by szymmis** [comment]
Yeah, when NODE_ENV is set to production dev dependencies are not installed with yarn. The problem is that we are using Vite to resolve dist files directory. I don't want to resign from this feature, but your case definitely needs to be solved. Thanks for letting me know!

**Comment by patryk-smc** [comment]
@szymmis Since it's just about pointing to the dist folder, I ended up hard-coding the path in my fork. For but the lib users, it seems to me that it would make sense to have them provide the path to the dist folder.

**Comment by szymmis** [comment]
Do you have `vite.config.js` in your production environment or is it a file that you omit? From the screen you sent I guess that you have that file present even when serving from heroku.

I'm asking about this because I want to know if it is a good idea to read `vite.config.js` directly as a text file and extracting dist path that way, because that's really the only thing I need from the config in production mode right now. That way I'm dropping the dependency for Vite in production mode and we can even make some defaults as you said (/dist as it is the default in Vite).

**Comment by szymmis** [comment]
I've just released v0.9.0 with changes presented in #64 so you can check it out and let me know if there are some problems or possible improvements. Thanks a lot for raising this issue @patryk-smc. Always great to hear suggestions!
