### ISSUE TITLE
create vite-express bug

### ISSUE THREAD

**Issue by BryceBlankinship** [szymmis/vite-express#63]
create vite-express command is generating folders with invisible characters, I have to rename the folder to what I intended it to be so I can cd into it. Not a breaking bug but annoying

**Comment by szymmis** [comment]
Hi @BryceBlankinship, can you give an example of such ill-named directory? What kind of invisible characters are those, whitespaces or something?

**Comment by BryceBlankinship** [comment]
macos, it would start with a $ or ~ or have some slashes, its different everytime. Not sure if this makes a difference but im running the command out of the vscode terminal, which can have some permissions issues sometimes. You can't see the characters unless you `ls` the directory then it will show.

**Comment by BryceBlankinship** [comment]
ok just tried create-vite, the issue is with yarn, npm does it fine, yarn doesn't even run it. I tried your command with npm instead of yarn, and it works fine. I would just change your docs to use npm to run commands.

**Comment by BryceBlankinship** [comment]
otherwise great tool! It works exactly how I was hoping it would work. I picked it up to bootstrap our UIs at work that still require an express backend and don't want to move to an opinionated fullstack framework.

**Comment by szymmis** [comment]
Thank you, always great to hear when somebody finds this tool useful. If you have any feedback or ideas feel free to let me know!

I'll also ask one last question if that's not a problem, what versions of yarn and npm do you have?

It might be a good idea to swap docs to npm but I want to be sure what is the cause of that issue because it is really strange.

Thanks a lot for raising this issue!

**Comment by BryceBlankinship** [comment]
yarn v1.22.17 and npm v9.5.1

probably a good idea to update my yarn
