### ISSUE TITLE
How to compile the server code to JS

### ISSUE THREAD

**Issue by relaxedleaf** [szymmis/vite-express#67]
Currently when we run `yarn build`, only the UI gets built. And we start the server using `ts-node`, is there a way for us to compile the server code to plain JavaScript code so that we can directly run the server using `node`?

**Comment by gaoyang** [comment]
@relaxedleaf  I'm also looking for a solution, at the moment I'm trying to compile the server js with `rollup`

**Comment by szymmis** [comment]
Hi guys. Yeah it is absolutely possible to compile your TypeScript code into JavaScript. You can use all sort of available bundlers but I'll show an example using `rollup` because that's what @gaoyang is looking for.

1. You need to have `rollup` installed 
```console
npm install --save-dev rollup
# or
yarn add --dev rollup
```
2. You need to create a config file for rollup. You can name it whatever you want, but sticking to convetions we'll name it `rollup.config.js`
```javascript
// rollup.config.js
import typescript from "@rollup/plugin-typescript";

export default {
  input: "src/server/main.ts",
  output: {
    dir: "dist",
    format: "cjs",
  },
  external: ["express", "vite-express"],
  plugins: [typescript({ module: "ESNext", exclude: "src/client/**" })],
};
```
For reference about config options please refer to [rollup docs](https://rollupjs.org/configuration-options/)

3. We are using [typescript plugin](https://www.npmjs.com/package/@rollup/plugin-typescript) for rollup so we need to install it 

```console
npm install --save-dev @rollup/plugin-typescript tslib
# or
yarn add --dev @rollup/plugin-typescript tslib
```

4. We can run the compilation using this command

```console
npx rollup -c rollup.config.js --bundleConfigAsCjs
# or
yarn rollup -c rollup.config.js --bundleConfigAsCjs
```
- `-c rollup.config.js` is used to pass correct config file to rollup
- `--bundleConfigAsCjs` is used because config is defined using ESModules syntax

If you have any further questions, feel free to ask.

**Comment by North101** [comment]
Thanks! I was able to keep it in one config by making the server builder a vite plugin

```typescript
import json from '@rollup/plugin-json'
import typescript from '@rollup/plugin-typescript'
import react from '@vitejs/plugin-react'
import rollup from 'rollup'
import { PluginOption, defineConfig } from 'vite'

const viteExpressBuilder = (): PluginOption => {
  return {
    name: 'Vite Express Builder',
    async buildEnd() {
      const config = await rollup.rollup({
        input: './src/server/main.ts',
        external: ['express', 'vite-express'],
        plugins: [
          typescript({ module: 'ESNext', exclude: 'src/client/**' }),
          json(),
        ],
      })
      await config.write({
        dir: './dist/server',
        format: 'cjs',
      })
    }
  }
}

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    outDir: './dist/client',
  },
  plugins: [
    react(),
    viteExpressBuilder(),
  ],
})
```

**Comment by paulineramos** [comment]
@odahcam I had the same error and had to import `rollup` as the following to fix it:
```typescript
import * as rollup from 'rollup';
```
