### ISSUE TITLE
Deploy to fly.io?

### ISSUE THREAD

**Issue by BryceBlankinship** [szymmis/vite-express#77]
Hey there @szymmis, great project as I've mentioned before, im trying to deploy this to fly.io, and it detects a node app, I'm not familiar with Docker, but have you ever deployed a project of this before? Is there a docker file you can add? This is what fly.io gives me and it doesn't work... mostly with the /app part:

```
# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=20.3.1
FROM node:${NODE_VERSION}-slim as base

LABEL fly_launch_runtime="Node.js"

# Node.js app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="production"


# Throw-away build stage to reduce size of final image
FROM base as build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install -y build-essential pkg-config python-is-python3

# Install node modules
COPY --link package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production=false

# Copy application code
COPY --link . .

# Build application
RUN yarn run build

# Remove development dependencies
RUN yarn install --production=true


# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app /app

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "node", "index.js" ]

```

**Comment by szymmis** [comment]
Hi @BryceBlankinship, can you give me some logs of the errors that you get when trying to build this image? Or are you getting errors on some other step?

I haven't deployed `vite-express` with Docker before nor used fly.io, but I'm sure will be able to figure out something out.

When trying to build the image locally I had to change NODE_VERSION to 18, because i was getting weird errors with the version that is specified in your Dockerfile. Then you have to make sure that `CMD [ "node", "index.js" ]` is point to the right command, the command that you use to run your server. If you use `create-vite-express` template then that correct CMD for that would be `CMD [ "yarn", "start" ]`. If you do use the template then there are some other changes that you need to make. (I need to make changes to the template myself so that it will be possible to run it out of the box in such environment that you have, mostly maybe add typescript compilation etc., but that's for the future).

Let me know if that info helps you move in any direction, and if you'll be able to provide some logs or more information, I'll try to help you a little bit more.

**Comment by BryceBlankinship** [comment]
So I tried making a brand new vite-express project and deploying with no changes, and the problem is coming from vite config, getting this:
`Error: Cannot find module '@vitejs/plugin-react'`

I tried npm installing it again, but no resolution. I believe the issue is actually with the fly.io-generated Dockerfile that is using /app as a folder.

How much of this Dockerfile is actually necessary to run the app? I'll try to fix it, but I don't have much experience with Docker.

@szymmis If you've ever deployed from a dockerfile before, can you send it over? It shouldn't matter the platform if they accept Dockerfiles... fly.io is just a nice UI wrapper for AWS EC2 instances essentially.

```
# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=20.3.1
FROM node:${NODE_VERSION}-slim as base

LABEL fly_launch_runtime="Node.js"

# Node.js app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="production"


# Throw-away build stage to reduce size of final image
FROM base as build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install -y build-essential pkg-config python-is-python3

# Install node modules
COPY --link package-lock.json package.json ./
RUN npm ci --include=dev

# Copy application code
COPY --link . .

# Build application
RUN npm run build

# Remove development dependencies
RUN npm prune --omit=dev


# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app /app

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "npm", "run", "start" ]
```

**Comment by BryceBlankinship** [comment]
Ok so I have made this slimmed down version:

```
# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=20.3.1
FROM node:${NODE_VERSION}-slim as base

LABEL fly_launch_runtime="Node.js"

# Set production environment
ENV NODE_ENV="production"

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "npm", "start" ]
```

And the issue is still present:

`  5:54:37 PM [vite-express] Running in production mode
  failed to load config from /app/vite.config.js
  node:internal/modules/cjs/loader:1072
    const err = new Error(message);
                ^
  Error: Cannot find module '@vitejs/plugin-react'
  Require stack:
  - /app/vite.config.js
  - /app/node_modules/vite/dist/node/chunks/dep-75f53616.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1072:15)
      at Module._load (node:internal/modules/cjs/loader:925:27)
      at Module.require (node:internal/modules/cjs/loader:1139:19)
      at require (node:internal/modules/helpers:121:18)
      at Object.<anonymous> (/app/vite.config.js:36:35)
      at Module._compile (node:internal/modules/cjs/loader:1257:14)
      at _require.extensions.<computed> [as .js] (file:///app/node_modules/vite/dist/node/chunks/dep-75f53616.js:66204:24)
      at Module.load (node:internal/modules/cjs/loader:1115:32)
      at Module._load (node:internal/modules/cjs/loader:962:12)
      at Module.require (node:internal/modules/cjs/loader:1139:19) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/app/vite.config.js',
      '/app/node_modules/vite/dist/node/chunks/dep-75f53616.js'
    ]`

I checked my .dockerignore and found nothing for vite.config.js, so no idea what the solution is here. I'll keep digging around and learning Docker so I can try to solve this

**Comment by BryceBlankinship** [comment]
Ok so I have changed the Image from node:20.3.1-slim to node:12, and now have this error at runtime:

`UnhandledPromiseRejectionWarning: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from /app/node_modules/vite-express/dist/main.js`

**Comment by BryceBlankinship** [comment]
Ok @szymmis I solved it, but this needs to be looked into further. Something is happening where the node_modules is not getting used properly (others seem to have an issue with Vite as well) its not necessarily an issue with your plugin, more just Vite in general. The interim solution is to make sure you push node_modules folder as well (not ideal since it is massive) to the container, instead of building on the container. So this meant removing node_modules from .dockerignore

**Comment by szymmis** [comment]
You are very close to solving that case @BryceBlankinship :sweat_smile:. There is indeed problem with `Vite` and `@vitejs/plugin-react` being listed as devDependencies. If you want to make minimal changes, the only thing that you need to do is to run `npm install` in your Dockerfile in development mode, so that all necessary dependencies will be installed and then `vite-express` will be able to run. Basically you need to change `npm install` into `npm install --production=false` 

Your Dockerfile would look like this

```Dockerfile
# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=20.3.1
FROM node:${NODE_VERSION}-slim as base

LABEL fly_launch_runtime="Node.js"

# Set production environment
ENV NODE_ENV="production"

WORKDIR /app
COPY package*.json ./
# This line was changed
RUN npm install --production=false 
COPY . .
EXPOSE 3000
CMD [ "npm", "start" ]
```

You are also right saying that this is something that I need to take care of as I stated in my previous comments. Basically there is a problem in `vite-express` needing `vite` even in production to resolve `vite.config.js`. That's why there is a problem with devDependencies not being installed when you have env `NODE_ENV=productin` set when running `npm install` (that's the reason why we are using `npm install --production=false` instead.)

 You could also use [`viteless` mode](https://github.com/szymmis/vite-express#-viteless-mode), but I'm not really happy with how it works so I recommend just installing devDependencies in your Dockerfile.

I'll definitely look into that, and try to make running `vite-express` in production mode completely Vite agnostic out of the box without the need to basically duplicate your configuration, but that's something that needs to be carefully though of so I don't have much time for that right now.

I hope that helps, if you have any more questions feel free to continue this issue.
