### ISSUE TITLE
ViteExpress.build() takes no parameters

### ISSUE THREAD

**Issue by tony-0tis** [szymmis/vite-express#79]
ViteExpress.build() takes no parameters, so Vite itself starts the build with process.env.NODE_ENV = 'production'
To avoid this, just pass the options = {mode: 'something'} object to vite.build(options)

**Comment by szymmis** [comment]
Hi @tony-0tis, I believe that build step is tied to production mode, so I don't think that is is possible to run build in development mode. If you want to set options for Vite you should just use `vite.config.js`.

If there is some usecase I don't understand, feel free to describe it!

**Comment by szymmis** [comment]
Is there any diffrrence in output when you run build in development vs production mode? I'm asking because I don't know if there is any, and as I said, I'm just guessing by looking at the documentation and seeing that `Vite.build()` is taking configuration object as a parameter, the same as defined in Vite config. That's why I made the function the way it is. I guess that doesn't really matter because I want to deprecate this function in order to make vite-express completely viteless in production mode.

But it is really interesting to know that someone is using this method. Either way, thanks a lot for pointing this out!

**Comment by tony-0tis** [comment]
Here is my build config in vite.config.js file
build:{
     outDir: join(__dirname, 'build'),
     emptyOutDir: true
     watch: {},
     manifest: true
     sourcemap: process.env.NODE_ENV !== 'production' ? 'inline' : null,
     rollupOptions: {
       input: join(__dirname, 'client/client.mjs')
     }
   },
There is a **watch** here, there is a **sourcemap**. **Watch** allows you to restart the build. **sourcemap** allows you to see scripts as they are on the front and debug.
I start the server and at the end of **ViteExpress.build()**, which does the build (and since the watch mode is on, it does this every time the files change), which is picked up by index.html.ejs;

**Comment by szymmis** [comment]
I believe that you might be misusing Vite. You shouldn't be using vite build in development at all.

In development Vite starts a server that serves all the necessary files for you app to work, all the script etc. You don't build the app in that mode at all, you just connect directly to the Vite server. Thats what happens when using plain Vite

What vite-express does is it connects your Express app to your Vite app automaticaly as soon as you do `ViteExpress.listen()`, no need to do anything besides that when you are in development.

When you want to deploy your app you need to do Vite build but you can just use the CLI to do that, also in that mode you don't need to configure anything as vite-express will just start serving your static files that `vite build` generated.

You can see the [templates](https://github.com/szymmis/vite-express/tree/master/create-vite-express/TEMPLATES) directory in `create-vite-express` for an example of the setup.

**Comment by tony-0tis** [comment]
I agree that running a build in development mode makes no sense 99% of the time.
But I decided to try different modes, including launching a build with the ability to reload changes. I plan to use this on a production server, with the ability to automatically rebuild files. 
"start": "node server.mjs build=false env=development",
"build": "node server.mjs build=true env=production",
"debug": "node server.mjs build=true env=development",
Where env turns into process.env.NODE_ENV, and build enables build mode, with scripts loaded from build. With env=development, build also includes sourcemap

**Comment by szymmis** [comment]
Yeah, by using build instead of default dev way you lose HMR and Hot Reload, but if you have a use case for that, go for it. As I said, you can just use vite config as you do right now to configure the build.

That means that I'll just proceed and close that issue as I don't plan to make any changes to that function.

If you have any more questions feel free to just continue this thread!

Thanks a lot for sharing your input and presenting a really interesting use case.
