### ISSUE TITLE
How to use vitest?

### ISSUE THREAD

**Issue by BryceBlankinship** [szymmis/vite-express#86]
Hey @szymmis, we are beginning to use your plugin everywhere at my job (which is a lot of repos), and we are migrating from jest to vitest. A coworker of mine had an issue grabbing some HTML with vitest to validate its content... do you have a preferred way of doing this? Not sure if our app being served by express is causing the issue, or if it is a separate thing. Here is the error:
```
@vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
```
We checked out that link but it didn't resolve our issue. Not sure if you know of any projects that use your plugin with vitest, I'd like to see if there's any difference in config. Whatever you can advise will be helpful. Thanks!

**Comment by szymmis** [comment]
Hi @BryceBlankinship, unfortunately I don't know any project that uses `vitest` in `vite-express` app and I also didn't use it myself. How I test `vite-express` served HTML is by using puppetier so that react has possibility to render. Maybe that's something you can look into, you can take a look at a test suite but I use some custom testing code instead of `vitest` (I plan to migrate to vitest in the future)

Do these tests work when using `jest`? How and when do you extract this HTML, can you show me some snippet? Maybe I'll be able to deduct something out of it.

**Comment by szymmis** [comment]
Hi @BryceBlankinship, any updates on this issue? Or should I just close it, as a month have passed.

**Comment by BryceBlankinship** [comment]
Yea you can close he found a solution thanks
