### ISSUE TITLE
deployment to vercel or netlify isn't working for API calls.

### ISSUE THREAD

**Issue by elvis-ndubuisi** [szymmis/vite-express#9]
When project is deployed, client pages renders normally but API calls to '/endpoint/... from client/main.ts returns a 404 error - SyntaxError: Unexpected token 'T', "The page c"... is not valid JSON

**Comment by szymmis** [comment]
Hi @elvis-ndubuisi, I don't have much experience with hosting express apps on Vercel nor Netlify, but I think that the better choice would be to host your server on something capable of running the process continuously instead of running the app as serverless. That's because when integrating Vite and serving static files in production we make express behave like a fullstack application, and as far as I'm concerned hosting express on Vercel makes sense only when you have nothing more than API paths, without any static files serving logic etc.
What works for me personally is to host your server on some kind of VPS server.

I hope that I made things a little bit more clear, but I'm not capable of providing more information and I'll close this issue as it isn't quite related to the package itself.
