### ISSUE TITLE
Deprecation of Vite CJS Node API in Vite 6

### ISSUE THREAD

**Issue by pontusva** [szymmis/vite-express#96]
Vite CJS Node API is deprecated in Vite 6 and is scheduled for removal.

For more details: https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated

I'll be actively working on addressing this deprecation in my fork. However, if I encounter any challenges or need guidance during the process, I plan to use this issue to seek assistance.

**Comment by szymmis** [comment]
Fantastic, keep me updated as soon as any problems will pop up. Thanks a lot for doing this! ❤️

**Comment by pontusva** [comment]
Hi,

I'm having issues with warnings related to TypeScript servers. Everything works with frontend tests and the React server without TypeScript.

The specific error I'm facing is "Unknown file extension ".ts," leading to a crash. It seems to be related to setting the type to module in package.json. If I omit this setting, warnings appear on the frontend.

Any ideas?  😅

**Comment by szymmis** [comment]
Hello,
I think that I have a solution for that problem. There are issues with `ts-node` and ESM syntax, but we can migrate to [`tsx`](https://www.npmjs.com/package/tsx). Not only it just works, they also claim to be faster than `ts-node` because `tsx` relies on `esbuild` as opposed to using `tsc` for TS compilation.

To use `tsx` with `nodemon` we need to changes dev scripts from:

```json
"dev": "nodemon src/server/main.ts -w src/server"

```

to something like:

```json
"dev": "nodemon -w src/server -x tsx src/server/main.ts"
```

So we are using `-x` option in nodemon to execute arbitrary script instead of running node/ts-node. 

Let me know if that helps!

**Comment by pontusva** [comment]
Alright, sounds like a good idea because this seems to work :) Only verified it for the first React-ts server, but i
ll see if I can fix all later today with this info.

Thanks :)
